[tool.poetry]
name = "nonebot-plugin-genshin-cos"
version = "0.1.0"
description = "米游社原神cos图获取"
authors = ["divandia <106718176+Cvandia@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "nonebot_plugin_genshin_cos"}]

[tool.poetry.dependencies]
python = ">=3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
